### PR TITLE
Fix #1: Add config options for custom ruler color.

### LINKED ISSUE #1: Allow to define colors for each ruler

### PR DESCRIPTION
**Pull request by Osmose**
Figured updating on _any_ config change wouldn't hurt. Couldn't figure out a way to have a default option without adding a second config option that enables the custom color.

### CODE REVIEW

**Comment by Problematic** [comment]
Thanks for this! I'll check it out when I'm at my computer later today.

**Comment by Problematic** [comment]
Sorry about the delay. Thank you.

**Comment by alepore** [comment]
I'm pretty new to atom.. i was wondering: can't we just have a single color option with a good default (maybe the same as the "core" ruler package)?

**Comment by Osmose** [comment]
> I'm pretty new to atom.. i was wondering: can't we just have a single color option with a good default (maybe the same as the "core" ruler package)?

I tested it and there's no way to have an empty value for a color preference, and since the color of the ruler is dependent on the currently active theme, we can't really have a "default" color that looks good without just choosing some random color or using the checkbox + color setting that we ended up using in this PR.

It'd be nice if we could but atom just doesn't allow for it right now. :(

**Pull request merged**
